Add sub-env $BIN_DIR/steps/run-app-script

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -123,16 +123,10 @@ export PKG_CONFIG_PATH=/app/.heroku/vendor/lib/pkg-config:$BUILD_DIR/.heroku/ven
 # Switch to the repo's context.
 cd $BUILD_DIR
 
-# Warn for lack of Procfile.
-if [[ ! -f Procfile ]]; then
-  puts-warn 'Warning: Your application is missing a Procfile. This file tells Heroku how to run your application.'
-  puts-warn 'Learn more: https://devcenter.heroku.com/articles/procfile'
-fi
-
 # Experimental pre_compile hook.
-bpwatch start pre_compile
-  source $BIN_DIR/steps/hooks/pre_compile
-bpwatch stop pre_compile
+# bpwatch start pre_compile
+#   source $BIN_DIR/nhooks/pre_compile
+# bpwatch stop pre_compile
 
 # If no requirements.txt file given, assume `setup.py develop` is intended.
 if [ ! -f requirements.txt ]; then
@@ -185,6 +179,13 @@ set -e
 
 mkdir -p $(dirname $PROFILE_PATH)
 
+# Missing runtime-dyno-metadata
+if [[ ! -f $ENV_DIR/HEROKU_APP_NAME ]]; then
+  puts-warn 'Error: you need enabme runtime-dyno-metadata'
+  puts-warn 'Learn more: https://devcenter.heroku.com/articles/dyno-metadata'
+  exit 1
+fi
+
 # Install Python.
 source $BIN_DIR/steps/python
 
@@ -212,9 +213,19 @@ source $BIN_DIR/steps/gdal
 # Install dependencies with Pip.
 source $BIN_DIR/steps/pip-install
 
+# Run script from app repository
+chmod +x $BIN_DIR/steps/run-app-script
+sub-env $BIN_DIR/steps/run-app-script
+
 # Django collectstatic support.
 sub-env $BIN_DIR/steps/collectstatic
 
+# Error in lack of Procfile.
+if [[ ! -f Procfile ]]; then
+  puts-warn 'Error: Your application is missing a Procfile. This file tells Heroku how to run your application.'
+  puts-warn 'Learn more: https://devcenter.heroku.com/articles/procfile'
+  exit 1
+fi
 
 # Create .profile script for application runtime environment variables.
 set-env PATH '$HOME/.heroku/python/bin:$PATH'
